### ISSUE TITLE
cp: cannot stat ‘/var/task/ffmpeg’: No such file or directory

### ISSUE THREAD

**Issue by dotjiwa** [deek87/lamba-thumbnailer#5]
Whew.. since the ARN to the layer provided is not working, I have tried every which way to get the layer working myself. I am quite familiar with AWS Lambda and have added many layers in the past, but this one has evaded me. 

I keep getting this error below when trying to run this library with the sample code provided. I have both this library and ffmpeg installed as layers. 

Any guidance you can provide would be much appreciated. Thank you. 

Here is the trace: 

Response:
{
  "errorType": "TypeError",
  "errorMessage": "lvt.S3 is not a constructor",
  "trace": [
    "TypeError: lvt.S3 is not a constructor",
    "    at Runtime.exports.handler (/var/task/index.js:9:15)",
    "    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"
  ]
}

Request ID:
"3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a"

Function logs:
START RequestId: 3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a Version: $LATEST
2020-10-05T21:12:47.378Z	3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a	INFO	{"Records":[{"eventVersion":"2.1","eventSource":"aws:s3","awsRegion":"us-west-2","eventTime":"2020-10-05T19:37:04.616Z","eventName":"ObjectCreated:Put","userIdentity":{"principalId":"AWS:AIDAYSRDSSHZ3OKC4T7VU"},"requestParameters":{"sourceIPAddress":"44.230.17.147"},"responseElements":{"x-amz-request-id":"F4334B0026CB45A7","x-amz-id-2":"srU/E35rWxvHs/iFUQvaetR4QwJVv/qT39HC2DcEXB/GQ8YEEF3QToZjveCPkDc2kmD5z2/HspFe3wH8husCU6Vjc4F1MWyt"},"s3":{"s3SchemaVersion":"1.0","configurationId":"ZjkyZDY2ODItNzU3Mi00NzM0LWIwMWMtYTJjNjgyNjVkMDAy","bucket":{"name":"contentjaguar-hosted.com","ownerIdentity":{"principalId":"AIOAF98JYAQFE"},"arn":"arn:aws:s3:::contentjaguar-hosted.com"},"object":{"key":"generated-videos/1-1/jagcomp-c1_a5_swim_418430c8-2782-410f-8404-07e461370eb3_0-d.mp4","size":6294286,"eTag":"db0a7bbf202ec7cccbe4d421ea3d9ac5","sequencer":"005F7B75E1BCB6F5FB"}}}]}
2020-10-05T21:12:47.385Z	3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a	ERROR	Invoke Error 	{"errorType":"TypeError","errorMessage":"lvt.S3 is not a constructor","stack":["TypeError: lvt.S3 is not a constructor","    at Runtime.exports.handler (/var/task/index.js:9:15)","    at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)"]}
2020-10-05T21:12:47.405Z	3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a	INFO	ffmpeg permissions couldnt be set
2020-10-05T21:12:47.408Z	3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a	INFO	Error: Command failed: cp /var/task/ffmpeg /tmp/ffmpeg && chmod 755 /tmp/ffmpeg
cp: cannot stat ‘/var/task/ffmpeg’: No such file or directory

    at ChildProcess.exithandler (child_process.js:303:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:483:12)
    at maybeClose (internal/child_process.js:1021:16)
    at Socket.<anonymous> (internal/child_process.js:443:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:483:12)
    at Pipe.<anonymous> (net.js:674:12) {
  killed: false,
  code: 1,
  signal: null,
  cmd: 'cp /var/task/ffmpeg /tmp/ffmpeg && chmod 755 /tmp/ffmpeg'
}
2020-10-05T21:12:47.408Z	3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a	INFO	
2020-10-05T21:12:47.408Z	3d9418e8-a9c9-4f94-96ba-0c0898cc2f7a	INFO	cp: cannot stat ‘/var/task/ffmpeg’: No such file or directory

**Comment by dotjiwa** [comment]
I was able to get around this by down-grading my lambda project from Node 12.x to 10.x, deploying the mentioned ffmpeg package (https://github.com/serverlesspub/ffmpeg-aws-lambda-layer), and going with a different code example all together : https://dev.to/benjaminadk/how-do-i-create-thumbnails-when-i-upload-a-video-aws-lambda-7l4 .

I know this github project was a predecessor to the aforementioned article, so credit to deek87 as well. Thanks. 

I hope this helps someone else. Cheers!
